// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0wb4b1tgfcLsJMW6dfKk0p6lj9gQD99o',
    appId: '1:425700343454:web:6ca120c0561fc47ba5858f',
    messagingSenderId: '425700343454',
    projectId: 'test-5e101',
    authDomain: 'test-5e101.firebaseapp.com',
    storageBucket: 'test-5e101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnzRbyTIv9HEa7pwYChJekPYTHw05rseQ',
    appId: '1:425700343454:android:6de7b2824bdbc485a5858f',
    messagingSenderId: '425700343454',
    projectId: 'test-5e101',
    storageBucket: 'test-5e101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwfU-uHmkJPrMEDI2JYB_4tUhHvpDAgo',
    appId: '1:425700343454:ios:49103d2d5a6be9b4a5858f',
    messagingSenderId: '425700343454',
    projectId: 'test-5e101',
    storageBucket: 'test-5e101.appspot.com',
    iosBundleId: 'com.test.testFirebase',
  );
}
